# Docker compose to run tickets service, environment for it and prometheus agent
# Run with following command: docker-compose -f docker-compose/kamon/zipkin-docker-compose.yml up -d
# Stop with following command: docker-compose -f docker-compose/kamon/zipkin-docker-compose.yml down
# After start open http://localhost:9411 to verify Zipkin is up and running
version: "3"
services:
  projects_service:
    extends:
      file: ../common-zipkin-docker-compose.yml
      service: projects_service
    networks:
      - tickets

  postgres:
    extends:
      file: ../common-zipkin-docker-compose.yml
      service: postgres
    networks:
      - tickets

  elasticsearch:
    extends:
      file: ../common-zipkin-docker-compose.yml
      service: elasticsearch
    networks:
      - tickets

  zookeeper:
    extends:
      file: ../common-zipkin-docker-compose.yml
      service: zookeeper
    networks:
      - tickets

  kafka-1:
    extends:
      file: ../common-zipkin-docker-compose.yml
      service: kafka-1
    networks:
      - tickets

  kafka-2:
    extends:
      file: ../common-zipkin-docker-compose.yml
      service: kafka-2
    networks:
      - tickets

  zipkin:
    extends:
      file: ../common-zipkin-docker-compose.yml
      service: zipkin
    networks:
      - tickets

  tickets_service:
    image: tickets_service_kamon
    container_name: tickets_service_kamon
    hostname: tickets_service
    restart: always
    environment:
      - APPLICATION_ELASTICSEARCH_URL=http://elasticsearch:9200
      - APPLICATION_POSTGRE_URL=jdbc:postgresql://postgres:5432/tickets?user=tickets_user&password=tickets_password
      - APPLICATION_POSTGRE_HOST=postgres
      - APPLICATION_KAFKA_URL=kafka-1:9092
      - APPLICATION_PROJECTS_URL=http://projects_service:10000
      - APPLICATION_ZIPKIN_HOST=zipkin
      - APPLICATION_ZIPKIN_PORT=9411
    networks:
      - tickets
    ports:
      - "10001:10001"
    depends_on:
      - projects_service
      - postgres
      - elasticsearch
      - zookeeper
      - kafka-1
      - kafka-2
      - zipkin

networks:
  tickets: