# See for more details: https://docs.datadoghq.com/tracing/setup_overview/open_standards/#otlp-ingest-in-datadog-agent
# Run with the following command: docker-compose -f docker-compose/opentelemetry/datadog-docker-compose.yml up -d
# Stop with the following command: docker-compose -f docker-compose/opentelemetry/datadog-docker-compose.yml down
version: "3"
services:
  projects_service:
    extends:
      file: ../common-environment-docker-compose.yml
      service: projects_service
    hostname: projects_service

  postgres:
    extends:
      file: ../common-environment-docker-compose.yml
      service: postgres

  elasticsearch:
    extends:
      file: ../common-environment-docker-compose.yml
      service: elasticsearch

  zookeeper:
    extends:
      file: ../common-environment-docker-compose.yml
      service: zookeeper

  kafka-1:
    extends:
      file: ../common-environment-docker-compose.yml
      service: kafka-1

  kafka-2:
    extends:
      file: ../common-environment-docker-compose.yml
      service: kafka-2

  opentelemetry-collector-contrib:
    build: ../docker-opentelemetry-collector-contrib
    container_name: opentelemetry-collector-contrib
    hostname: opentelemetry-collector-contrib
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
      - tickets
    ports:
      - "4317:4317"
      - "9411:9411"
      - "14250:14250"
      - "14268:14268"
      - "6831:6831"
      - "55680:55680"
      - "55681:55681"

  tickets_service:
    image: tickets_service_otel
    container_name: tickets_service_otel
    hostname: tickets_service
    restart: always
    environment:
      - OTEL_SERVICE_NAME=tickets_service
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector-contrib:4317
      - APPLICATION_ELASTICSEARCH_URL=http://elasticsearch:9200
      - APPLICATION_POSTGRE_URL=jdbc:postgresql://postgres:5432/tickets?user=tickets_user&password=tickets_password
      - APPLICATION_POSTGRE_HOST=postgres
      - APPLICATION_KAFKA_URL=kafka-1:9092
      - APPLICATION_PROJECTS_URL=http://projects_service:10000
    networks:
      - tickets
    ports:
      - "10001:10001"
    depends_on:
      - projects_service
      - postgres
      - elasticsearch
      - zookeeper
      - kafka-1
      - kafka-2
      - opentelemetry-collector-contrib

networks:
  tickets: