# Docker compose to run tickets service, environment for it and prometheus agent
# Run with following command: docker-compose -f docker-compose/opentelemetry/prometheus-docker-compose.yml up -d
# Stop with following command: docker-compose -f docker-compose/opentelemetry/prometheus-docker-compose.yml down
# After start open http://localhost:9090 to verify Prometheus is up and running
version: "3.9"
services:
  projects_service:
    extends:
      file: ../common-prometheus-docker-compose.yml
      service: projects_service
    hostname: projects_service
    networks:
      - tickets

  postgres:
    extends:
      file: ../common-prometheus-docker-compose.yml
      service: postgres
    hostname: postgres
    networks:
      - tickets

  elasticsearch:
    extends:
      file: ../common-prometheus-docker-compose.yml
      service: elasticsearch
    hostname: elasticsearch
    networks:
      - tickets

  zookeeper:
    extends:
      file: ../common-prometheus-docker-compose.yml
      service: zookeeper
    hostname: zookeeper
    networks:
      - tickets

  kafka-1:
    extends:
      file: ../common-prometheus-docker-compose.yml
      service: kafka-1
    hostname: kafka-1
    networks:
      - tickets

  kafka-2:
    extends:
      file: ../common-prometheus-docker-compose.yml
      service: kafka-2
    hostname: kafka-2
    networks:
      - tickets

  prometheus:
    extends:
      file: ../common-prometheus-docker-compose.yml
      service: prometheus
    hostname: prometheus
    networks:
      - tickets

  tickets_service:
    image: tickets_service_otel
    container_name: tickets_service_otel
    hostname: tickets_service
    restart: always
    environment:
      - OTEL_SERVICE_NAME=tickets_service
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_EXPORTER_PROMETHEUS_PORT=9094
      - OTEL_EXPORTER_PROMETHEUS_HOST=0.0.0.0
      - APPLICATION_ELASTICSEARCH_URL=http://elasticsearch:9200
      - APPLICATION_POSTGRE_URL=jdbc:postgresql://postgres:5432/tickets?user=tickets_user&password=tickets_password
      - APPLICATION_POSTGRE_HOST=postgres
      - APPLICATION_KAFKA_URL=kafka-1:9092
      - APPLICATION_PROJECTS_URL=http://projects_service:10000
    networks:
      - tickets
    ports:
      - "10001:10001"
      - "9094:9094"

networks:
  tickets: