# Docker compose to run environment for service-tickets and Zipkin instance.
# Run with the following command: docker-compose -f docker-compose/common-zipkin-docker-compose.yml up -d
# Stop with the following command: docker-compose -f docker-compose/common-zipkin-docker-compose.yml down
# After start open http://localhost:9411 to verify Zipkin is up and running
version: "3"
services:
  projects_service:
    extends:
      file: common-environment-docker-compose.yml
      service: projects_service
    networks:
      - tickets

  postgres:
    extends:
      file: common-environment-docker-compose.yml
      service: postgres
    networks:
      - tickets

  elasticsearch:
    extends:
      file: common-environment-docker-compose.yml
      service: elasticsearch
    networks:
      - tickets

  zookeeper:
    extends:
      file: common-environment-docker-compose.yml
      service: zookeeper
    networks:
      - tickets

  kafka-1:
    extends:
      file: common-environment-docker-compose.yml
      service: kafka-1
    networks:
      - tickets

  kafka-2:
    extends:
      file: common-environment-docker-compose.yml
      service: kafka-2
    networks:
      - tickets

  zipkin:
    image: openzipkin/zipkin:2
    hostname: zipkin
    container_name: zipkin
    restart: always
    networks:
      - tickets
    ports:
      - "9411:9411"

networks:
  tickets: