# See for more details: https://docs.splunk.com/Observability/gdi/opentelemetry/install-linux.html#docker
# NOTE: Replace `SPLUNK_ACCESS_TOKEN` and `SPLUNK_REALM` with yours and  run agent before app launch.
# Run with following command: docker-compose -f docker-compose/opentelemetry-splunk-docker-compose.yml up -d
# Stop with following command: docker-compose -f docker-compose/opentelemetry-splunk-docker-compose.yml down
version: "3"
services:
  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    environment:
      - SPLUNK_ACCESS_TOKEN=${SPLUNK_ACCESS_TOKEN}
      - SPLUNK_REALM=${SPLUNK_REALM}
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "6060:6060"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943"